name: Build EXE
on: [push, workflow_dispatch]
jobs:
  build_exes:
    strategy:
        matrix:
          version: ['', -PoE2]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Build EXEs
        run: 'msbuild PathOfBuilding-Launcher.vcxproj /p:configuration=release${{ matrix.version }} /p:platform=x64'
      - name: Archive EXE
        uses: actions/upload-artifact@v4
        with:
            name: Path of Building${{ matrix.version }}.exe
            path: '${{ github.workspace }}/x64/Release${{ matrix.version }}/Path of Building${{ matrix.version }}.exe'

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure CMake
        uses: threeal/cmake-action@v1.3.0
        with:
            options: CMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Archive PoB
        uses: actions/upload-artifact@v4
        with:
          name: PathOfBuilding
          path: "build/Path of Building"
      - name: Archive PoB2
        uses: actions/upload-artifact@v4
        with:
          name: PathOfBuilding-PoE2
          path: "build/Path of Building-PoE2"
